/*
     Copyright (C) 2012 Andrew Darqui

     This file is part of darqbot.

     darqbot is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.

     darqbot is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with darqbot.  If not, see <http://www.gnu.org/licenses/>.

     Contact: [website: http://www.adarq.org]
      email: andrew.darqui@g m a i l . c o m
*/
#ifndef FN_ALL_H
#define FN_ALL_H

int (*_bit_extract_bit_char)(unsigned char, int);
int (*_bit_pack_bit_char)(unsigned char *, int, int);
int (*_bit_pack_bit_char_set)(unsigned char *, int);
int (*_bit_pack_bit_char_clr)(unsigned char *, int);
bit_vector_t *(*_bit_vec_init)(int);
void (*_bit_vec_fini)(bit_vector_t **);
int (*_bit_vec_get_and_set)(bit_vector_t *);
void (*_bit_vec_clr)(bit_vector_t *, int);
void (*_bit_vec_zero)(bit_vector_t *);
void (*_bit_vec_set)(bit_vector_t *, int);
int (*_bit_vec_get)(bit_vector_t *, int);
int (*_bit_vec_scan)(bit_vector_t *, int);
char * (*_bit_vec_to_str)(bit_vector_t *);
void (*_bit_vec_from_str)(bit_vector_t *, char *);
void (*_bit_vec_from_num)(bit_vector_t *, unsigned long);
void (*_bit_vec_and)(bit_vector_t *, bit_vector_t *, bit_vector_t *);
void (*_bit_vec_or)(bit_vector_t *, bit_vector_t *, bit_vector_t *);
void (*_bit_vec_xor)(bit_vector_t *, bit_vector_t *, bit_vector_t *);
void (*_bit_vec_not)(bit_vector_t *);
void (*_bit_vec_add)(bit_vector_t *, bit_vector_t *, bit_vector_t *);
void (*_bit_vec_sub)(bit_vector_t *, bit_vector_t *, bit_vector_t *);
void (*_bit_vec_mul)(bit_vector_t *, bit_vector_t *, bit_vector_t *);
void (*_bit_vec_div)(bit_vector_t *, bit_vector_t *, bit_vector_t *);
void (*_bit_vec_and)(bit_vector_t *, bit_vector_t *, bit_vector_t *);
void (*_bit_vec_and)(bit_vector_t *, bit_vector_t *, bit_vector_t *);
int (*_bit_vec_3safe)(bit_vector_t *, bit_vector_t *, bit_vector_t *) ;
bot_t *(*_bot_init)(void);
int (*_bot_line_clear)(bot_t *);
int (*_bot_line_clear_bufs)(bot_t *);
void (*_bot_fini)(void *);
void (*_bot_fini_subs)(void *);
void (*_bot_sigend_handler)(int);
void (*_bot_atexit_handler)(void);
void (*_bot_sigpipe_handler)(int);
void (*_bot_sigchld_handler)(int);
void (*_bot_sigalrm_handler)(int);
void (*_bot_exit_handler)(int);
void (*_bot_fini_wrapper)(void);
void (*_bot_defaults)(bot_t *);
void (*_bot_test_stuff_init)(void);
int (*_change_server)(bot_t *);
int (*_bot_shouldreturn)(bot_t *);
void (*_bot_find_and_set_fd)(char *, int);
int (*_bot_parse_tag)(bot_t *, char *, int);
bot_t *(*_bot_init_and_turn_on)(char *);
void (*_bot_turn_on)(bot_t *, int);
void (*_bot_turn_off)(bot_t *);
void (*_bot_exchange_data)(bot_t *, bot_t *);
dlist_t *(*_bot_sub_add)(bot_t *, bot_t *);
bot_t *(*_bot_dup_sub)(bot_t *);
bot_t *(*_bot_dup)(bot_t *);
bot_t * (*_bot_find_tag)(char *);
bot_t * (*_bot_find_sub_by_tag)(bot_t * , char *);
bot_t * (*_bot_find_sub_by_id)(bot_t * , int);
pid_t (*_bot_fork_clean)(bot_t *);
void (*_bot_fork_clean_exit)(bot_t *); 
void (*_bot_copy_values)(bot_t * bot, char * nick, char * ident, char * host, char * to, char * in, char * out) ;
dlist_t ** (*_bot_all_find_dlist_by_bot_id)(bot_t *, dlist_t **);
bot_t *(*_bot_find_all_by_id)(int);
int (*_bot_daemon)(int, char **, bot_t **, char *, char *);


size_t (*_strlen)(const char *);
char * (*_strchr)(const char *, int);
char *(*_strrchr)(const char *, int);
char *(*_strcpy)(char *, const char *);
char *(*_strncpy)(char *, const char *, size_t);

int (*_true)(void);
int (*_false)(void);
int (*_val_int)(int);
char * (*_val_string)(char *);
void * (*_memset)(void *, int , size_t ) ;
void (*_bzero)(void *, size_t);
int (*_strcmp)(const char *, const char *);
int (*_strncmp)(const char *, const char *, size_t);
size_t (*_strlcpy)(char *, const char *, size_t);
size_t (*_strlcat)(char *, const char *, size_t);
int (*_usleep)(useconds_t);
char *(*_strdup)(const char *);
int (*_strcasecmp)(const char *, const char *);
int (*_strncasecmp)(const char *, const char *, size_t);
int (*_kill)(pid_t, int);
int (*_fileno)(FILE *);
int (*_isascii)(int);
int (*_setgroups)(size_t, const gid_t *);
void * (*_memcpy)(void *, const void *, size_t );
void * (*_memset)(void *, int, size_t);
int (*_printf)(const char *format, ...);
int (*_fprintf)(FILE *stream, const char *format, ...);
int (*_snprintf_buf)(char *str, size_t size, const char *format, ...);
int (*_vsnprintf_buf)(char *str, size_t size, const char *format, va_list ap);
char *(*_strcasestr)(const char *, const char *);
int (*_getopt)(int, char * const *, const char *);
FILE *(*_fmemopen)(void *, size_t, const char *);
char *(*_n_gethostbyname)(char *);
int (*_bot_network_raw_connect)(char *, int, int, int);
int (*_bot_network_raw_listen)(char *, int);
int (*_bot_network_raw_disconnect)(int);
int (*_bot_unset_evhooks)(bot_t *);
int (*_bot_set_evhooks)(bot_t *, void (*fn)(int, short, void *));
int (*_bot_unix_fd_send)(bot_t *, int, bot_gmod_elm_t*);
int (*_bot_unix_init)(void);
int (*_bot_unix_fini)(void);
void (*_bot_evhook_unix_accept)(int, short, void *);
void (*_bot_evhook_unix_read)(int, short, void *);
void (*_bot_unix_node_destroy)(void *);
char *(*_bot_find_confdir)(bot_t *);
int (*_conf_parse)(bot_t *);
int (*_bot_parse_logfile)(bot_t *, char *, int);
int (*_bot_parse_trace)(bot_t *, char *, int);
int (*_bot_parse_debug)(bot_t *, char *, int);
int (*_bot_parse_pmodules)(bot_t *, char *, int);
int (*_bot_parse_gmodules)(bot_t *, char *, int, char *);
void (*_conf_fix)(bot_t *);
char *(*_conf_get_proto)(int);
char *(*_conf_get_type)(int);
void (*_bot_evhook_console)(int, short, void *);
void (*_console_info_print)(bot_t *);
void (*_console_xmodreload)(int, char *);
void (*_console_xmodunload)(int, char *);
void (*_console_xmodload)(int, char *);
void (*_console_modreload)(char *);
void (*_console_modunload)(char *);
void (*_console_modload)(char *);
void (*_console_pmodreload)(char *);
void (*_console_pmodunload)(char *);
void (*_console_pmodload)(char *);
void (*_console_gmodreload)(char *);
void (*_console_gmodunload)(char *);
void (*_console_gmodload)(char *);
void (*_bot_evhook_console)(int, short, void *);
int (*_bot_help_console)(bot_t *);
void (*_console_info)(bot_t *, char *);
void (*_console_info_print)(bot_t *);
void (*_console_tag_pare)(bot_t *, char *);
void (*_console_parse)(bot_t *, char *);
void (*_console_print_all)(int);
void (*_console_print_all_bot)(bot_t *, int);
control_t *(*_control_init)(void);
control_sub_t *(*_control_sub_init)(void);
dlist_t *(*_control_add_fdpass)(control_t *, int);
int (*_control_get_fdpass)(dlist_t **);
int (*_control_get_fdpass_find)(dlist_t **);
dlist_t * (*_control_bot_add)(bot_t *, control_t *);
void (*_control_bot_del)(bot_t *, dlist_t *);
void (*_control_fini)(void *);
void (*_control_sub_fini)(void *);
bot_t * (*_environ_set)(bot_t *, char *, char *);
bot_t *(*_environ_set_withnum)(bot_t *, int, char *);
char *(*_environ_get)(bot_t *, char *);
bot_t * (*_environ_unset)(bot_t *, char *);
bot_t *(*_environ_destroy)(bot_t *);
bot_t *(*_environ_destroy_args)(bot_t *);
bot_t *(*_environ_add_args1)(bot_t *, char *, char *);
bot_t * (*_environ_debugprint)(bot_t *);
char *(*_environ_sub_envs)(bot_t *, char *);
fd_link_t * (*_fd_link_add)(dlist_t **, int, struct event, struct sockaddr_in *, struct sockaddr_un *);
fd_link_t * (*_fd_link_find)(dlist_t **, int);
int (*_fd_link_del)(dlist_t **, int, void (*cleanup)(fd_link_t *));
void (*_fd_link_destroy)(dlist_t **, void (*cleanup)(fd_link_t *));
void (*_fd_link_cleanup)(fd_link_t *);
void (*_fd_link_set_cur)(dlist_t **, fd_link_t *, int);
void (*_fd_link_print)(fd_link_t *);
char *(*_fd_link_get_latest_host)(bot_t *, char *, char *);
dlist_t *(*_files_get_listing)(bot_t *, char *, int);
void (*_files_get_listing_run)(bot_t *, char *, int, dlist_t **);
void (*_files_destroy)(bot_t *, dlist_t **);
void (*_global_defaults)(void);
void (*_global_conf_parse)(void);
char *(*_global_conf_dir)(void);
int (*_global_chroot)(void);
int (*_chroot)(const char *);
int (*_setreuid)(uid_t, uid_t );
int (*_setregid)(gid_t , gid_t);
void (*_global_core_unlimited)(void);
void (*_global_signal_hooks)(void);
void (*_global_signal_exit_hooks)(void);
void (*_global_on)(void);
void (*_global_off)(void);
void (*_global_fork_clean_stuff)(void);
int (*_global_parse_chroot)(char *, int);
int (*_global_parse_modules)(char *, int);
int (*_global_parse_pmodules)(char *, int);
int (*_global_parse_gmodules)(char *, int);
int (*_global_parse_trace)(char *, int);
int (*_global_parse_debug)(char *, int);
int (*_global_parse_sigprotect)(char *, int);
int (*_global_parse_timer_sort)(char *, int);
int (*_global_parse_timer_sleep)(char *, int);
int (*_global_parse_fd_unix_path) (char *, int );
void (*_global_signal_hooks_child)(void);
void (*_global_set_proc_ptrs)(int *, char **, char **);
void (*_global_getopt)(int, char **);
module_t *(*_gmodule_load)(char *);
module_t *(*_gmodule_unload)(module_t *);
void (*_gmodule_iolist)(void);
void (*_gmodule_timerlist)(void);
void (*_gmodule_list)(void);
char *(*_gmodule_path)(char *);
void (*_gmodule_load_all)(void);
void (*_bot_gxmodule_free)(void *);
bot_t *(*_gmodule_unload_all)(void);
void (*_bot_gmodule_run_stack)(bot_t *);
void (*_bot_gmodule_run_stack_new)(bot_t *);
void (*_bot_gmodule_run_stack_once)(bot_t *);
void (*_bot_gmodule_run_stack_new_once)(bot_t *);
void (*_bot_gmodule_elm_free)(void *);
void (*_bot_gmodule_run_control)(bot_t *, int, ...);
int (*_gmodule_up)(dlist_t *, bot_t *);
int (*_gmodule_down)(dlist_t *, bot_t *);
int (*_gmodule_destroy_up)(dlist_t *, bot_t *);
int (*_gmodule_destroy_down)(dlist_t *, bot_t *);
int (*_gmodule_control_up)(dlist_t *, bot_t *);
int (*_gmodule_control_down)(dlist_t *, bot_t *);
int (*_gmodule_up_then_down)(dlist_t *, bot_t *);
void (*_gmodule_fix_data_up)(bot_t *);
void (*_gmodule_fix_data_down)(bot_t *);
void (*_gmodule_fix_data_out_to_in)(bot_t *);
void (*_gmodule_fix_data_in_to_out)(bot_t *);
bot_gmod_elm_t * (*_gmodule_get_gmod)(dlist_t *);
bot_gmod_elm_t * (*_gmodule_get_gmod_next)(dlist_t *);
void (*_gmodule_update)(module_t *, char *);
dlist_t *(*_gmodule_find_by_trig_dptr)(char *);
module_t *(*_gmodule_find_by_trig)(char *);
module_t *(*_gmodule_find_by_name)(char *);
void (*_gmodule_lock)(char *);
void (*_gmodule_unlock)(char *);
bot_gmod_elm_t *(*_gmodule_find_gmod)(bot_t *, char *, char *);
dlist_t *(*_gmodule_find_gmod_dptr)(bot_t *, char *, char *);
bot_gmod_elm_t *(*_gmodule_find_latest_gmod)(bot_t *, char *, char *);
dlist_t *(*_gmodule_find_latest_gmod_dptr)(bot_t *, char *, char *);
void (*_gmodule_gmod_print)(bot_gmod_elm_t *);
void (*_gmodule_update_stats)(void);
void (*_gmodule_sort)(void);
dlist_t *(*_bot_gmodule_dup_bot_gmodules)(bot_t *);
void (*_gmodule_off)(bot_t *);
void (*_gmodule_off_bot)(bot_t *);
void (*_gmodule_set_can_pass_up)(bot_gmod_elm_t *);
void (*_gmodule_set_can_pass_down)(bot_gmod_elm_t *);
void (*_gmodule_set_has_run)(bot_gmod_elm_t*);
dlist_t *(*_gmod_cache_enqueue)(dlist_t **, int ,char *, int);
bot_gmod_cache_elm_t * (*_gmod_cache_dequeue)(dlist_t **);
void (*_gmod_cache_free)(void *);
void (*_gmodule_keepalive_on)(bot_t *);
void (*_gmodule_keepalive_off)(bot_t *);
void (*_gmodule_parse_common_options)(bot_t *, bot_gmod_elm_t *, char *);
int (*_gmodule_up_force)(dlist_t *, bot_t *);
int (*_gmodule_down_force)(dlist_t *, bot_t *);
void (*_gxmodule_free)(void *);
int (*_matchchar)(int, int);
int (*_matchchar_str)(char *);
int (*_matchchar_seed)(int);
char *(*_matchchar_retstr)(int);
     size_t (*_strlcpy_safe)(char *, const char *, size_t);
     size_t (*_strlcat_safe)(char *, const char *, size_t);
char * (*_sNULL)(char *);
int (*_vsnprintf_safe)(char *, size_t , const char *, va_list);
char * (*_str_unite)(const char * msg, ...);
char *(*_str_unite_static)(const char *, ...);
char * (*_str_unite_foralloc)(const char * msg, ...);
int (*_strstrip_nl) (char *);
char * (*_eat_whitespace)(char *);
int (*_strstrip_chars)(char *, char *);
char * (_strtokpos)(char *, int );
int (*_strcasecmp_len)(const char *, const char *);
int (*_strlcatfmt_safe)(char *, int, char *, ...);
char *(*_strstr_len)(char *, char *, int);
int (*_strlcat_bot_safe)(char *, char *, int);
int (*_strlcatfmt_bot_safe)(char *, int, char *, ...);
int (*_strprepend_bot_safe)(char *, char *, int);
char *(*_strdup_char)(char);
char *(*_strdup_int)(int);
char *(*_strdup_len)(char *, int);
int (*_charcat_safe)(char *, char, int);
int (*_charcat_bot_safe)(char *, char, int);
char *(*_strtok_nonalpha)(char *);
char *(*_strtokdup_str)(char *, char *);
char *(*_xstrcasestr)(char *, char *);
char *(*_strcasestr_len)(char *, char *, int);
char *(*_strcasestr2)(char *, char *);
char *(*_strcasestr_unique)(char *, char *);
char *(*_strzero_bot_safe)(char *, size_t);
char *(*_str_find_sep)(char *);
int (*_str_clean_sep)(char *);
int (*_str_clean_sep_shrink)(char *, int);
int (*_str_transform_pipes)(char *);
int (*_str_untransform_pipes)(char *);
char *(*_strtokbionic)(char *, const char *, int *);
 char *(*_strtokbionic_nonalpha)(char *, int *);
int (*_str_clean_nl)(char *, int);
int (*_snprintf_safe)(char *,size_t, const char *, ...);
int (*_capsup)(char *);
int (*_capsdown)(char *);
int (*_str_isclean)(char *, int (*fn)(int));
int (*_str_apply)(char *,int(*fn)(int));
int (*_str_apply_is)(char *, int (*fn)(int));
int (*_iskeychars)(int );
int (*_ctoi)(int);
int (*_itoc)(int);
char *(*_itostr)(int);
void *(*_memcopy)(char *, char *, size_t, size_t);
int (*_str_shrink_quotes)(char *);
int (*_isbinary)(int );
int (*_memcpy_bot_safe)(char *, int, char *, int);
char *(*_strrchr_len)(const char *, int, int);
int (*_str_last_char_replace)(char *, int, int);
int (*_str_has_newline)(char *);
int (*_str_shrink_chars)(char *, char *);
int (*_str_shrink_spaces_to_one)(char *);
int (*_str_shrink_chars_and_replace)(char *, char *, char );
int (*_str_sum)(char *);
int (*_MAX_FMT)(char *, ...);
char * (*_strchr_str)(const char *, const char *, int *);
char * (*_str_replace)(char *, char *, char *);
int (*_istrig)(int);
int (*_isprog)(int);
char *(*_ret_trig)(char *);
int (*_dl_str_unite)(dlist_t **, const char *, ...);
int (*_dl_str_dup)(dlist_t **, const char *);
void (*_dl_str_debug)(dlist_t **);
void (*_dl_str_print)(dlist_t **);
void (*_dl_str_destroy)(dlist_t **);
char *(*_str_create_spaces)(int);
char *(*_str_match)(const char *, int, int, ...);
int (*_strstrip_chars_fmt)(char *, int, ...);
int (*_strstrip_chars_fmtv2)(char *, int, ...);
int (*_seg)(void *);
memdup_t *(*_memdup)(char *, int);
void (*_memdup_free)(void *);
module_t  *(*_module_load)(char *);
module_t *(*_module_unload)(module_t *);
void (*_module_timerlist)(void);
void (*_module_iolist)(void);
void (*_module_list)(void);
char *(*_module_path)(char *);
void (*_module_load_all)(void);
void (*_module_deactivate_dptr)(void *);
void (*_module_deactivate)(void *);
void (*_xmodule_free_destroy)(void *);
bot_t *(*_module_unload_all)(void);
void (*_module_add_subtrigs)(module_t *, char *);
void (*_module_update)(module_t *, char *);
dlist_t *(*_module_find_by_trig_dptr)(char *);
module_t *(*_module_find_by_trig)(char *);
module_t *(*_module_find_by_name)(char *);
void (*_module_lock)(char *);
void (*_module_unlock)(char *);
void (*_module_update_stats)(void);
void (*_module_sort)(void);
void (*_modules_off)(void);
bot_t *(*_mongodb_init)(bot_t *);
bot_t *(*_mongodb_fini)(bot_t *);
int (*_mongodb_insert_key)(bot_t *, char *, char *, char *, char *, ...);
char *(*_mongodb_retrieve_key)(bot_t *, char *, char *, char *);
int (*_mongodb_remove_key)(bot_t *, char *, char *);
int (*_mongodb_insert_key_stat)(bot_t *, char *, char *, int);
int (*_mongodb_retrieve_key_stat)(bot_t *, char *, char *);
int (*_mongodb_update_key_stat)(bot_t *, char *, char *, int);
dlist_t *(*_mongodb_dump_keyvalue)(bot_t *, char *);
void (*_mongodb_destroy_keyvalue)(bot_t *, dlist_t **);
void (*_mongodb_free_keyvalue)(void *);
mongo_argument_t ** (*_mongodb_fmt_retrieve)(bot_t *, char *, mongo_argument_t *);
int (*_mongodb_arg_destroy)(bot_t *, mongo_argument_t **);
void (*_mongodb_arg_free)(void *);
void (*_mongodb_arg_print)(bot_t *, mongo_argument_t **);
void (*_mongodb_arg_print_arg)(mongo_argument_t *);
mongo_argument_t ** (*_mongodb_fmt_build_strings)(bot_t *, char *);
mongo_argument_t ** (*_mongodb_fmt_build_fmt)(bot_t *, char *, ...);
int (*_mongodb_fmt_insert_arg)(bot_t *, char *, mongo_argument_t **);
bson *(*_mongodb_bson_build)(bot_t *, char *, ...);
int (*_mongodb_bson_insert)(bot_t *, char *, bson *);
void (*_mongodb_bson_unfinished)(bson *);
char *(*_mongodb_bson_dump)(bson *);
char *(*_mongodb_bson_print_init)(const bson *);
void (*_mongodb_bson_print)(const bson *);
void (*_mongodb_bson_print_raw)(const char *, int);
bson * (*_mongodb_bson_get)(bot_t *, char *, char *, int, void *);
void (*_mongodb_drop_db)(char *);
int (*_sig_stoi)(char *);
char *(*_sig_itos)(int);
int (*_close_io_descriptors)(char *);
int (*_xdaemon)(int, int);
void (*_xsetproctitle)(char *);
char *(*_random_data)(int);
void (*_clean_environ)(void);
module_t *(*_pmodule_load)(char *);
module_t *(*_pmodule_unload)(module_t *);
void (*_pmodule_iolist)(void);
void (*_pmodule_timerlist)(void);
void (*_pmodule_list)(void);
char * (*_pmodule_path)(char *);
void (*_pmodule_load_all)(void);
void (*_bot_pxmodule_free)(void *);
bot_t *(*_pmodule_unload_all)(void);
void (*_pmodule_update)(module_t *, char *);
dlist_t *(*_pmodule_find_by_trig_dptr)(char *);
module_t *(*_pmodule_find_by_trig)(char *);
module_t *(*_pmodule_find_by_name)(char *);
void (*_pmodule_cur_set)(bot_t *(*fn)(dlist_t *, bot_t *), dlist_t *, bot_t *);
void (*_pmodule_cur_clear)(void);
bot_t *(*_pmodule_cur_run)(void);
bot_t *(*_pmodule_cur_run2)(bot_t *);
void (*_pmodule_lock)(char *);
void (*_pmodule_unlock)(char *);
void (*_pmodule_update_stats)(void);
void (*_pmodule_sort)(void);
void (*_nick_free)(void *);
void (*_server_free)(void *);
void (*_channel_free)(void *);
void (*_nick_add)(bot_t *, char *, char * , char *, char *, char *);
dlist_t *(*_chan_find)(bot_t *, char *);
dlist_t *(*_chan_del_user)(bot_t *, dlist_t *, char *);
dlist_t *(*_chan_add_user)(bot_t *, dlist_t *, char *);
dlist_t *(*_chan_find_user)(bot_t *, dlist_t *, char *);
bot_t *(*_chan_find_tag)(char *);
int (*_randchar)(int, int);
int (*_randchar_str)(char *);
int (*_randchar_seed)(int);
char *(*_randchar_retstr)(int);
int (*_relink_req_pack_buf)(char *, int, int, int, int);
int (*_relink_req_pack_buf_hello)(char *, int);
int (*_relink_pack_buf_relink)(char *, int, char *, int, int, int);
int (*_relink_req_pack_buf_relink_new)(char *, int, char *);
int (*_relink_req_pack_buf_query)(char *, int, int);
int (*_relink_req_pack_buf_query_links)(char *, int);
int (*_relink_req_pack_buf_query_subs)(char *, int);
int (*_relink_req_pack_buf_query_reload)(char *, int);
int (*_relink_req_pack_buf_destroy_link)(char *, int, int);
int (*_relink_req_pack_buf_destroy_sub)(char *, int, int);
int (*_relink_req_pack_buf_destroy_all)(char *, int);
int (*_relink_req_pack_buf_reload)(char *);
int (*_relink_res_pack_buf)(char *, int, int, int);
int (*_relink_res_pack_buf_new)(char *, int);
int (*_relink_res_pack_buf_old)(char *, int);
int (*_relink_res_pack_buf_error)(char *, int );
int (*_relink_res_buf_result_string)(char *, int, char *);
int (*_relink_find_buf_result_string)(char *, int, char **, int *);
int (*_relink_pack_buf_data)(char *, int, char *, int);
int (*_relink_find_buf_data)(char *, int, char **, int *);
void (*_relink_packet_print)(char *, relink_control_pkt_t *);
void (*_relink_packet_ntoh)(relink_control_pkt_t *);
void (*_packet_relink_hton)(relink_control_pkt_t *);
int (*_relink_ispacket)(relink_control_pkt_t *);
int (*_relink_packet_len)(char *);
dlist_t * (*_relink_buf_to_dlist)(char *, int);
int (*_safe_close)(int);
void (*_safe_event_set)(struct event *, int , short , void (*fn)(int, short, void *), void *) ;
int (*_safe_event_add)(struct event *, struct timeval *) ;
int (*_safe_event_del)(struct event *);
int (*_stat_inc)(bot_t *, char *);
int (*_stat_retcnt)(bot_t *, char *);
void (*_timer_handler)(int);
void (*_timer_handler_new)(int);
void (*_timer_set)(void);
void (*_timer_unset)(void);
void (*_timer_shouldwerun)(void);
dlist_t * (*_tokenize)(bot_t *, char *, int , char *);
void (*_tokenize_destroy)(bot_t *, dlist_t **);
char **(*_tokenize_array)(bot_t *, char *, int, char *, int *);
void (*_tokenize_destroy_array)(bot_t *, char **);
char *(*_tokenize_find_closing_bracket)(char *, int);
char *(*_tokenize_find_inside_of_brackets)(char *, int);
char ** (*_tokenize_str2argv)(char *, int *, int);
unique_t *(*_unique_create)(bot_t *, dlist_t **, int);
unique_t * (*_unique_find)(bot_t *, dlist_t **);
void *(*_unique_get)(bot_t *, dlist_t **);
unique_t * (*_unique_delete)(bot_t *, dlist_t **, void (*)(void *));
void (*_unique_free)(void *);
void (*_unique_destroy)(bot_t *, dlist_t **, void (*)(void *));
char *(*_unique_bu2str)(unique_t *,int);
DB *(*_xdb_open)(char *);
int (*_xdb_write)(DB *, char *, char *);
void (*_xdb_fini)(DB *);
xdb_pair_t *(*_xdb_get)(DB *, char *);
xdb_pair_t * (*_xdb_get_recnum)(DB *, int);
int (*_xdb_count)(DB *);
xdb_pair_t *(*_xdb_pair_create)(char *, int, char *, int);
void (*_xdb_pair_destroy)(void *);
xdb_pair_t *(*_xdb_pair_find_by_key)(dlist_t *, char *);
module_t *(*_xmodule_load)(int, char *);
module_t *(*_xmodule_unload)(int,module_t *,char *);
void (*_xmodule_list)(int );
void (*_xmodule_iolist)(int);
void * (*_xmodule_iolist_traverse)(void *, void *);
void (*_xmodule_timerlist)(int);
void * (*_xmodule_timerlist_traverse)(void *, void *);
void (*_xmodule_load_all)(int);
bot_t *(*_xmodule_unload_all)(int);
char * (*_xmodule_path)(int, char *);
module_t *(*_xmodule_find_by_trig)(int, char *);
dlist_t *(*_xmodule_find_by_trig_dptr)(int, char *);
module_t *(*_xmodule_find_by_name)(int, char *);
void (*_xmodule_update)(int, module_t *, char *);
void (*_xmodule_lock)(int, char *);
void (*_xmodule_unlock)(int, char *);
void (*_xmodule_unload_everything)(void);
void (*_xmodule_update_stats)(int);
void (*_xmodule_sort)(int);
void *(*_xmodule_sort_traverse)(void *, void *);
void (*_xmodule_parse_style)(char *);
int (*_xmodule_avl_compare)(const void *, const void *, void *);
void (*_xmodule_avl_free)(void *, void *);
void *(*_xmodule_tree_match_by_name)(void *, void *);
void * (*_xmodule_tree_print_node)(void *);
void (*_xmodule_del_timer)(char *);
dlist_t *(*_xmodule_find_timer)(char *);
void (*_xmodule_add_timer)(module_t *);
void (*_xmodule_del_timer)(char *);
dlist_t *(*_xmodule_find_iohook)(char *);
void (*_xmodule_add_iohook)(module_t *);
void (*_xmodule_del_iohook)(char *);
module_t *(*_xmodule_dup_mirror)(module_t *, char *, char *, char *);
void (*_xmodule_add_subtrigs)(module_t *);
void *(*_xmodule_list_traverse)(void *, void *);
dlist_t ** (*_xmodule_type_to_dl)(int);
dlist_t ** (*_xmodule_typeio_to_dl)(int);
dlist_t ** (*_xmodule_typetimer_to_dl)(int);
void * (*_xmodule_unload_traverse)(void *, void *);
void *(*_xmodule_traverse_unload_all)(void *, void *);
dlist_t *(*_xmodule_insert)(dlist_t **, module_t *);
void (*_xmodule_zero)(module_t *);
xpid_t *(*_xpid_add)(bot_t *, pid_t );
void (*_xpid_destroy)(bot_t *, int);
void (*_xpid_del)(bot_t *, pid_t);
void (*_xpid_free)(void *);
void (*_xpid_console_print)(bot_t *, char *);
void (*_xpid_waitpid)(void);
void (*_console_zmodreload)(char *);
void (*_console_zmodunload)(char *);
void (*_console_zmodload)(char *);
void (*_zmodule_iolist)(void);
void (*_zmodule_timerlist)(void);
void (*_zmodule_list)(void);
void (*_zmodule_lock)(void);
void (*_zmodule_unlock)(void);
void (*_zmodule_unload_all_except)(char *, ...);
void (*_zmodule_lock_arg)(char *);
void (*_zmodule_unlock_arg)(char *);
void (*_zmodule_prune)(void);


#endif
